//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace LOE.Common.Entities.V3_1 {
    using System.Diagnostics.CodeAnalysis;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities", IsNullable=false)]
    [ExcludeFromCodeCoverage]
    public partial class CatalogResult {
        
        private CatalogChange[] catalogEntriesField;
        
        private string currentPageNumField;
        
        private string totalPagesField;
        
        private System.DateTime utcUpdatesFromField;
        
        private System.DateTime utcUpdatesToField;
        
        private CatalogResultExtension extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CatalogChange[] CatalogEntries {
            get {
                return this.catalogEntriesField;
            }
            set {
                this.catalogEntriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CurrentPageNum {
            get {
                return this.currentPageNumField;
            }
            set {
                this.currentPageNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotalPages {
            get {
                return this.totalPagesField;
            }
            set {
                this.totalPagesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UtcUpdatesFrom {
            get {
                return this.utcUpdatesFromField;
            }
            set {
                this.utcUpdatesFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UtcUpdatesTo {
            get {
                return this.utcUpdatesToField;
            }
            set {
                this.utcUpdatesToField = value;
            }
        }
        
        /// <remarks/>
        public CatalogResultExtension Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class CatalogChange {
        
        private ProductCatalogMeta catalogMetaField;
        
        private bool isDeletedField;
        
        private bool isDeletedFieldSpecified;
        
        /// <remarks/>
        public ProductCatalogMeta CatalogMeta {
            get {
                return this.catalogMetaField;
            }
            set {
                this.catalogMetaField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDeletedSpecified {
            get {
                return this.isDeletedFieldSpecified;
            }
            set {
                this.isDeletedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GameCatalogMeta))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class ProductCatalogMeta {
        
        private BundledItems bundledItemsField;
        
        private string descriptionField;
        
        private string fullTitleField;
        
        private Price[] pricingField;
        
        private RelatedProducts relatedProductsField;
        
        private string skuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BundledItems BundledItems {
            get {
                return this.bundledItemsField;
            }
            set {
                this.bundledItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FullTitle {
            get {
                return this.fullTitleField;
            }
            set {
                this.fullTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Price[] Pricing {
            get {
                return this.pricingField;
            }
            set {
                this.pricingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RelatedProducts RelatedProducts {
            get {
                return this.relatedProductsField;
            }
            set {
                this.relatedProductsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class BundledItems {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class CatalogResultExtension {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class GameCatalogMetaExtension {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class ProductVideoExtension {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class ProductVideo {
        
        private string videoDefinitionField;
        
        private string[] videoFileUrlsField;
        
        private ProductVideoExtension extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string VideoDefinition {
            get {
                return this.videoDefinitionField;
            }
            set {
                this.videoDefinitionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] VideoFileUrls {
            get {
                return this.videoFileUrlsField;
            }
            set {
                this.videoFileUrlsField = value;
            }
        }
        
        /// <remarks/>
        public ProductVideoExtension Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class ProductImages {
        
        private string boxArtFileUrlField;
        
        private string iconFileUrlField;
        
        private string[] screenshotFileUrlsField;
        
        /// <remarks/>
        public string BoxArtFileUrl {
            get {
                return this.boxArtFileUrlField;
            }
            set {
                this.boxArtFileUrlField = value;
            }
        }
        
        /// <remarks/>
        public string IconFileUrl {
            get {
                return this.iconFileUrlField;
            }
            set {
                this.iconFileUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] ScreenshotFileUrls {
            get {
                return this.screenshotFileUrlsField;
            }
            set {
                this.screenshotFileUrlsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class OnlineCapabilities {
        
        private Range onlineCoOpPlayersField;
        
        private bool onlineContentDownloadField;
        
        private bool onlineLeaderBoardsField;
        
        private Range onlineMultiPlayerField;
        
        private bool onlineVoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Range OnlineCoOpPlayers {
            get {
                return this.onlineCoOpPlayersField;
            }
            set {
                this.onlineCoOpPlayersField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlineContentDownload {
            get {
                return this.onlineContentDownloadField;
            }
            set {
                this.onlineContentDownloadField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlineLeaderBoards {
            get {
                return this.onlineLeaderBoardsField;
            }
            set {
                this.onlineLeaderBoardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Range OnlineMultiPlayer {
            get {
                return this.onlineMultiPlayerField;
            }
            set {
                this.onlineMultiPlayerField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlineVoice {
            get {
                return this.onlineVoiceField;
            }
            set {
                this.onlineVoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class Range {
        
        private string maxField;
        
        private string minField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class OfflineCapabilities {
        
        private bool cameraField;
        
        private bool cameraFieldSpecified;
        
        private Range coOpPlayersField;
        
        private bool dolbyDigitalField;
        
        private bool dolbyDigitalFieldSpecified;
        
        private Range playersField;
        
        private Range systemLinkField;
        
        /// <remarks/>
        public bool Camera {
            get {
                return this.cameraField;
            }
            set {
                this.cameraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CameraSpecified {
            get {
                return this.cameraFieldSpecified;
            }
            set {
                this.cameraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Range CoOpPlayers {
            get {
                return this.coOpPlayersField;
            }
            set {
                this.coOpPlayersField = value;
            }
        }
        
        /// <remarks/>
        public bool DolbyDigital {
            get {
                return this.dolbyDigitalField;
            }
            set {
                this.dolbyDigitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DolbyDigitalSpecified {
            get {
                return this.dolbyDigitalFieldSpecified;
            }
            set {
                this.dolbyDigitalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Range Players {
            get {
                return this.playersField;
            }
            set {
                this.playersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Range SystemLink {
            get {
                return this.systemLinkField;
            }
            set {
                this.systemLinkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnknownRating))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GrbRating))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FpbRating))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BrazilRating))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KmrbRating))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OflcRating))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UskRating))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PegiPortugalRating))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PegiFinlandRating))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CeroRating))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PegiRating))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EsrbRating))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class Rating {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class UnknownRating : Rating {
        
        private string[] ratingDescriptorsField;
        
        private string ratingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] RatingDescriptors {
            get {
                return this.ratingDescriptorsField;
            }
            set {
                this.ratingDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        public string RatingName {
            get {
                return this.ratingNameField;
            }
            set {
                this.ratingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class GrbRating : Rating {
        
        private string[] ratingDescriptorsField;
        
        private string ratingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] RatingDescriptors {
            get {
                return this.ratingDescriptorsField;
            }
            set {
                this.ratingDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        public string RatingName {
            get {
                return this.ratingNameField;
            }
            set {
                this.ratingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class FpbRating : Rating {
        
        private string[] ratingDescriptorsField;
        
        private string ratingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] RatingDescriptors {
            get {
                return this.ratingDescriptorsField;
            }
            set {
                this.ratingDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        public string RatingName {
            get {
                return this.ratingNameField;
            }
            set {
                this.ratingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class BrazilRating : Rating {
        
        private string[] ratingDescriptorsField;
        
        private string ratingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] RatingDescriptors {
            get {
                return this.ratingDescriptorsField;
            }
            set {
                this.ratingDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        public string RatingName {
            get {
                return this.ratingNameField;
            }
            set {
                this.ratingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class KmrbRating : Rating {
        
        private string[] ratingDescriptorsField;
        
        private string ratingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] RatingDescriptors {
            get {
                return this.ratingDescriptorsField;
            }
            set {
                this.ratingDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        public string RatingName {
            get {
                return this.ratingNameField;
            }
            set {
                this.ratingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class OflcRating : Rating {
        
        private string[] ratingDescriptorsField;
        
        private string ratingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] RatingDescriptors {
            get {
                return this.ratingDescriptorsField;
            }
            set {
                this.ratingDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        public string RatingName {
            get {
                return this.ratingNameField;
            }
            set {
                this.ratingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class UskRating : Rating {
        
        private string[] ratingDescriptorsField;
        
        private string ratingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] RatingDescriptors {
            get {
                return this.ratingDescriptorsField;
            }
            set {
                this.ratingDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        public string RatingName {
            get {
                return this.ratingNameField;
            }
            set {
                this.ratingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class PegiPortugalRating : Rating {
        
        private string[] ratingDescriptorsField;
        
        private string ratingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] RatingDescriptors {
            get {
                return this.ratingDescriptorsField;
            }
            set {
                this.ratingDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        public string RatingName {
            get {
                return this.ratingNameField;
            }
            set {
                this.ratingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class PegiFinlandRating : Rating {
        
        private string[] ratingDescriptorsField;
        
        private string ratingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] RatingDescriptors {
            get {
                return this.ratingDescriptorsField;
            }
            set {
                this.ratingDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        public string RatingName {
            get {
                return this.ratingNameField;
            }
            set {
                this.ratingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class CeroRating : Rating {
        
        private string[] ratingDescriptorsField;
        
        private string ratingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] RatingDescriptors {
            get {
                return this.ratingDescriptorsField;
            }
            set {
                this.ratingDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        public string RatingName {
            get {
                return this.ratingNameField;
            }
            set {
                this.ratingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class PegiRating : Rating {
        
        private string[] ratingDescriptorsField;
        
        private string ratingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] RatingDescriptors {
            get {
                return this.ratingDescriptorsField;
            }
            set {
                this.ratingDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        public string RatingName {
            get {
                return this.ratingNameField;
            }
            set {
                this.ratingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class EsrbRating : Rating {
        
        private string[] ratingDescriptorsField;
        
        private string ratingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] RatingDescriptors {
            get {
                return this.ratingDescriptorsField;
            }
            set {
                this.ratingDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        public string RatingName {
            get {
                return this.ratingNameField;
            }
            set {
                this.ratingNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class GamePurchaseDownloadUrl {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class RelatedProducts {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class PriceExtension {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class Price {
        
        private decimal amountField;
        
        private string currencyField;
        
        private string priceTypeField;
        
        private System.DateTime validFromField;
        
        private System.DateTime validToField;
        
        private PriceExtension extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidTo {
            get {
                return this.validToField;
            }
            set {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        public PriceExtension Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [ExcludeFromCodeCoverage]
    public partial class GameCatalogMeta : ProductCatalogMeta {
        
        private string developerField;
        
        private GamePurchaseDownloadUrl gamePurchaseDownloadUrlField;
        
        private Rating gameRatingField;
        
        private OfflineCapabilities offlineCapabilitiesField;
        
        private OnlineCapabilities onlineCapabilitiesField;
        
        private ProductImages productImagesField;
        
        private ProductVideo[] productVideosField;
        
        private string publisherField;
        
        private System.DateTime releaseDateField;
        
        private GameCatalogMetaExtension extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Developer {
            get {
                return this.developerField;
            }
            set {
                this.developerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GamePurchaseDownloadUrl GamePurchaseDownloadUrl {
            get {
                return this.gamePurchaseDownloadUrlField;
            }
            set {
                this.gamePurchaseDownloadUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Rating GameRating {
            get {
                return this.gameRatingField;
            }
            set {
                this.gameRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OfflineCapabilities OfflineCapabilities {
            get {
                return this.offlineCapabilitiesField;
            }
            set {
                this.offlineCapabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OnlineCapabilities OnlineCapabilities {
            get {
                return this.onlineCapabilitiesField;
            }
            set {
                this.onlineCapabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProductImages ProductImages {
            get {
                return this.productImagesField;
            }
            set {
                this.productImagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ProductVideo[] ProductVideos {
            get {
                return this.productVideosField;
            }
            set {
                this.productVideosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Publisher {
            get {
                return this.publisherField;
            }
            set {
                this.publisherField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReleaseDate {
            get {
                return this.releaseDateField;
            }
            set {
                this.releaseDateField = value;
            }
        }
        
        /// <remarks/>
        public GameCatalogMetaExtension Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities", IsNullable=false)]
    [ExcludeFromCodeCoverage]
    public partial class TokenInfo {
        
        private System.DateTime lastUpdateOfStatusField;
        
        private string promotionNameField;
        
        private System.Nullable<System.DateTime> redemptionDateTimeField;
        
        private string tokenClassNameField;
        
        private string tokenStatusField;
        
        /// <remarks/>
        public System.DateTime LastUpdateOfStatus {
            get {
                return this.lastUpdateOfStatusField;
            }
            set {
                this.lastUpdateOfStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PromotionName {
            get {
                return this.promotionNameField;
            }
            set {
                this.promotionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> RedemptionDateTime {
            get {
                return this.redemptionDateTimeField;
            }
            set {
                this.redemptionDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TokenClassName {
            get {
                return this.tokenClassNameField;
            }
            set {
                this.tokenClassNameField = value;
            }
        }
        
        /// <remarks/>
        public string TokenStatus {
            get {
                return this.tokenStatusField;
            }
            set {
                this.tokenStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CatalogResult", Namespace="http://schemas.datacontract.org/2004/07/LOE.Common.Entities.V3_1")]
    [System.Xml.Serialization.XmlRootAttribute("CatalogResult", Namespace="http://schemas.datacontract.org/2004/07/LOE.Common.Entities.V3_1", IsNullable=false)]
    [ExcludeFromCodeCoverage]
    public partial class CatalogResult1 {
        
        private CatalogChange1[] catalogEntriesField;
        
        private string currentPageNumField;
        
        private string totalPagesField;
        
        private System.DateTime utcUpdatesFromField;
        
        private System.DateTime utcUpdatesToField;
        
        private CatalogResultExtension1 extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CatalogChange1[] CatalogEntries {
            get {
                return this.catalogEntriesField;
            }
            set {
                this.catalogEntriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CurrentPageNum {
            get {
                return this.currentPageNumField;
            }
            set {
                this.currentPageNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotalPages {
            get {
                return this.totalPagesField;
            }
            set {
                this.totalPagesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UtcUpdatesFrom {
            get {
                return this.utcUpdatesFromField;
            }
            set {
                this.utcUpdatesFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UtcUpdatesTo {
            get {
                return this.utcUpdatesToField;
            }
            set {
                this.utcUpdatesToField = value;
            }
        }
        
        /// <remarks/>
        public CatalogResultExtension1 Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CatalogChange", Namespace="http://schemas.datacontract.org/2004/07/LOE.Common.Entities.V3_1")]
    [ExcludeFromCodeCoverage]
    public partial class CatalogChange1 {
        
        private ProductCatalogMeta1 catalogMetaField;
        
        /// <remarks/>
        public ProductCatalogMeta1 CatalogMeta {
            get {
                return this.catalogMetaField;
            }
            set {
                this.catalogMetaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GameCatalogMeta1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ProductCatalogMeta", Namespace="http://schemas.datacontract.org/2004/07/LOE.Common.Entities.V3_1")]
    [ExcludeFromCodeCoverage]
    public partial class ProductCatalogMeta1 {
        
        private BundledItems bundledItemsField;
        
        private string descriptionField;
        
        private int fulfillmentTypeField;
        
        private string fullTitleField;
        
        private Price1[] pricingField;
        
        private RelatedProducts relatedProductsField;
        
        private string skuField;
        
        private string returnTypeField;
        
        private ExtendedMetadata extendedMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BundledItems BundledItems {
            get {
                return this.bundledItemsField;
            }
            set {
                this.bundledItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int FulfillmentType {
            get {
                return this.fulfillmentTypeField;
            }
            set {
                this.fulfillmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FullTitle {
            get {
                return this.fullTitleField;
            }
            set {
                this.fullTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Price1[] Pricing {
            get {
                return this.pricingField;
            }
            set {
                this.pricingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RelatedProducts RelatedProducts {
            get {
                return this.relatedProductsField;
            }
            set {
                this.relatedProductsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReturnType {
            get {
                return this.returnTypeField;
            }
            set {
                this.returnTypeField = value;
            }
        }
        
        /// <remarks/>
        public ExtendedMetadata ExtendedMetadata {
            get {
                return this.extendedMetadataField;
            }
            set {
                this.extendedMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Price", Namespace="http://schemas.datacontract.org/2004/07/LOE.Common.Entities.V3_1")]
    [ExcludeFromCodeCoverage]
    public partial class Price1 {
        
        private decimal amountField;
        
        private string currencyField;
        
        private string priceTypeField;
        
        private System.DateTime validFromField;
        
        private System.DateTime validToField;
        
        private PriceExtension1 extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidTo {
            get {
                return this.validToField;
            }
            set {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        public PriceExtension1 Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="PriceExtension", Namespace="http://schemas.datacontract.org/2004/07/LOE.Common.Entities.V3_1")]
    [ExcludeFromCodeCoverage]
    public partial class PriceExtension1 {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/LOE.Common.Entities.V3_1")]
    [ExcludeFromCodeCoverage]
    public partial class ExtendedMetadata {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="GameCatalogMeta", Namespace="http://schemas.datacontract.org/2004/07/LOE.Common.Entities.V3_1")]
    [ExcludeFromCodeCoverage]
    public partial class GameCatalogMeta1 : ProductCatalogMeta1 {
        
        private string developerField;
        
        private GamePurchaseDownloadUrl gamePurchaseDownloadUrlField;
        
        private Rating gameRatingField;
        
        private OfflineCapabilities offlineCapabilitiesField;
        
        private OnlineCapabilities onlineCapabilitiesField;
        
        private ProductImages productImagesField;
        
        private ProductVideo[] productVideosField;
        
        private string publisherField;
        
        private System.DateTime releaseDateField;
        
        private GameCatalogMetaExtension1 extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Developer {
            get {
                return this.developerField;
            }
            set {
                this.developerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GamePurchaseDownloadUrl GamePurchaseDownloadUrl {
            get {
                return this.gamePurchaseDownloadUrlField;
            }
            set {
                this.gamePurchaseDownloadUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Rating GameRating {
            get {
                return this.gameRatingField;
            }
            set {
                this.gameRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OfflineCapabilities OfflineCapabilities {
            get {
                return this.offlineCapabilitiesField;
            }
            set {
                this.offlineCapabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OnlineCapabilities OnlineCapabilities {
            get {
                return this.onlineCapabilitiesField;
            }
            set {
                this.onlineCapabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProductImages ProductImages {
            get {
                return this.productImagesField;
            }
            set {
                this.productImagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities", IsNullable=false)]
        public ProductVideo[] ProductVideos {
            get {
                return this.productVideosField;
            }
            set {
                this.productVideosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Publisher {
            get {
                return this.publisherField;
            }
            set {
                this.publisherField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReleaseDate {
            get {
                return this.releaseDateField;
            }
            set {
                this.releaseDateField = value;
            }
        }
        
        /// <remarks/>
        public GameCatalogMetaExtension1 Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="GameCatalogMetaExtension", Namespace="http://schemas.datacontract.org/2004/07/LOE.Common.Entities.V3_1")]
    [ExcludeFromCodeCoverage]
    public partial class GameCatalogMetaExtension1 {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CatalogResultExtension", Namespace="http://schemas.datacontract.org/2004/07/LOE.Common.Entities.V3_1")]
    [ExcludeFromCodeCoverage]
    public partial class CatalogResultExtension1 {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
}
